In [1]:
from main import FilesDatabase
import pandas as pd

In [14]:
#FILE="/Users/alain/Library/CloudStorage/OneDrive-EducationVaud"
db = FilesDatabase.create("/Users/alain/Library/CloudStorage/OneDrive-EducationVaud")

# first file I created: zzzarchives/coding/Rpy-mc/BonjourMondeDeMinecraft.py in 2020-06-20 17:07:44

100%|██████████| 247869/247869 [00:13<00:00, 17928.68it/s]

In [9]:
db=db[db.ctime>="2020-06-20 17:07:44"]

In [ ]:
db=db.sort("size")
db

,size,n,ctime,mtime,atime,level
name,,,,,,
.,26287654129,247639,2024-10-23 13:40:53,2025-02-09 10:16:40,2025-02-09 10:16:41,0
zzzarchives,19646404626,245503,2025-02-01 15:07:54,2025-02-08 10:49:52,2025-02-08 10:49:52,1
zzzarchives/coding,9982068642,243047,2025-02-01 15:15:10,2025-02-01 15:17:12,2025-02-01 15:17:12,2
zzzarchives/autres,9196279327,2252,2025-02-01 15:13:39,2025-02-01 15:14:35,2025-02-01 15:14:35,2
Pictures,6557152786,1790,2024-10-21 02:16:13,2024-11-09 22:57:32,2024-11-09 22:57:32,1
...,...,...,...,...,...,...
zzzarchives/coding/Rpy/test-pip/pip/_vendor/urllib3/packages/__init__.py,0,1,2024-01-07 10:14:32,2024-01-07 10:14:30,2024-10-24 10:02:21,9
zzzarchives/coding/Rpy/test-pip/pip/_vendor/urllib3/contrib/_securetransport/__init__.py,0,1,2024-01-07 10:14:32,2024-01-07 10:14:30,2024-10-24 10:02:33,10
zzzarchives/coding/Rpy/test-pip/pip/_vendor/truststore/py.typed,0,1,2024-01-07 10:14:32,2024-01-07 10:14:30,2024-10-24 09:51:14,8
zzzarchives/coding/Rpy/test-pip/pip/_vendor/chardet/cli/__init__.py,0,1,2024-01-07 10:14:32,2024-01-07 10:14:28,2024-10-24 10:03:26,9
zzzarchives/coding/Rpy/test-pip/pip/_vendor/chardet/py.typed,0,1,2024-01-07 10:14:32,2024-01-07 10:14:28,2024-10-24 09:51:05,8

In [ ]:
db=db.sort("n")
db

                         size    n  ...               atime level
name                                ...
.                    16452124  228  ... 2025-02-08 12:16:57     0
files-timeline        3087580  120  ... 2025-02-09 11:26:45     1
files-timeline/.git   1994264   92  ... 2025-02-09 11:11:39     2
tetris               13175801   83  ... 2025-02-01 15:16:43     1
tetris/.git          10217953   78  ... 2024-11-03 10:56:25     2
...                       ...  ...  ...                 ...   ...
tetris/music.mp3      2944940    1  ... 2024-10-27 17:36:25     2
.DS_Store                8196    1  ... 2025-02-09 10:15:56     1
tetris/README.md          215    1  ... 2024-12-26 10:29:26     2
files-database/a/b          0    1  ... 2025-02-08 12:16:57     3
files-database/a/c          0    1  ... 2025-02-08 12:16:57     3

[228 rows x 6 columns]

In [22]:
db_by_time=db.sort("mtime",False)
db_by_time

                                   size   n  ...               atime level
name                                         ...
files-timeline/main.ipynb         31208   1  ... 2025-02-09 11:46:17     2
files-timeline/.git/objects     1963871  59  ... 2025-02-09 11:46:15     3
files-timeline/.git/FETCH_HEAD        0   1  ... 2025-02-08 14:52:57     3
files-timeline/test.ipynb         17666   1  ... 2025-02-09 11:46:04     2
files-timeline/__pycache__         6315   2  ... 2025-02-09 11:26:46     2
...                                 ...  ..  ...                 ...   ...
tetris/music.mp3                2944940   1  ... 2024-10-27 17:36:25     2
tetris/.git/HEAD                     21   1  ... 2024-10-27 17:35:39     3
tetris/README.md                    215   1  ... 2024-12-26 10:29:26     2
tetris/.git/description              73   1  ... 2024-10-27 17:35:37     3
tetris/.git/info/exclude            240   1  ... 2024-10-27 17:35:40     4

[228 rows x 6 columns]

In [7]:
"\\"

'\\'

In [11]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
import os
os.sep

'/'